version: "3"
services:
  myportfolio:
    container_name: portfolio
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql
    
  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql
    
  nginx:
    container_name: nginx
    image: jonasal/nginx-certbot
    restart: always
    environment:
      - CERTBOT_EMAIL=ishami11@live.com
      - RENEWAL_INTERVAL=8d
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - myportfolio
  
  # adding CERBOT service
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >-
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email ishami11@live.com --agree-tos --no-eff-email
             -d ishami-ru.duckdns.org
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot

volumes:
  mydatabase:
  nginx_secrets: